---
- name: Debian-SRC-Build | install dependencies
  apt:
   name={{ item }}
   update_cache=yes
   state=latest
  with_items:
   - make
   - gcc
   - tcl


- name: Debian-SRC-Build | Create group
  user:
   name=redis


- name: Debian-SRC-Build | Create user
  user:
   name=redis
   shell=/bin/false
   home={{ redis_install.directory }}
   groups=redis
   comment="redis server"


- name: Debian-SRC-Build | Create required directories
  file: 
   path={{ item }}
   state=directory
   owner=redis
   group=redis
  with_items:
   - /var/run/redis
   - /var/log/redis
   - /var/lib/redis


- name: Debian-SRC-Build | Download Redis src file
  get_url:
   url={{ redis_install.download_url }}
   dest=/usr/local/src/{{ redis_install.download_url | basename }}
   sha256sum={{redis_install.src_file_sha256}}


- name: Debian-SRC-Build | Extract the src Redis file
  unarchive:
   src=/usr/local/src/{{ redis_install.download_url | basename }}
   dest={{redis_install.directory}}
   copy=no


- name: Debian-SRC-Build | Create symlink {{ redis_install.directory }}/redis -> /opt/redis-{{redis_version}}
  file: 
   src="{{ redis_install.directory }}/redis-{{ redis_version }}" 
   dest="{{ redis_install.directory }}/redis"
   state=link


- name: Debian-SRC-Build | make
  command: "make"
  args:
   chdir: "{{ redis_install.directory }}/redis-{{ redis_version }}"


- name: Debian-SRC-Build | make test
  shell: "make test > test.log 2>&1"
  args:
   chdir: "{{ redis_install.directory }}/redis-{{ redis_version }}"


- name: Debian-SRC-Build | Create symlinks in /usr/bin
  file: 
   src="/opt/redis-{{ redis_version }}/src/{{ item }}"
   dest=/usr/bin/{{ item }}
   state=link
   owner=root
   group=root
   mode=0755
  with_items:
   - redis-benchmark
   - redis-check-aof
   - redis-check-dump
   - redis-cli
   - redis-server
   - redis-sentinel
