---
- name: Debian-SRC | Check if redis-server executable exsists to skip build
  stat: path="{{redis_install.directory}}/redis-{{redis_version}}"
  register: redis_server

- include: Debian-SRC-Build.yml
  when: not redis_server.stat.exists

- name: Debian-SRC | Copy the main redis.conf
  template: >
   src={{ redis_conf }}
   dest={{redis_install.directory}}/redis-{{redis_version}}/redis.conf
  notify: restart redis

- name: Debian-SRC | Copy upstart config
  template: >
   src=Debian/redis-server-upstart.j2
   dest=/etc/init.d/redis-server
   owner=root group=root mode=0755
