# ansible_distribution_release
#
# CenOS 7     - Core
# RedHat 6    - Santiago
# RedHat 7    - Maipo
# Ubuntu 14   - trusty
- name: Check for supported operating system on target
  fail:
    msg: "The operating system of the target machine ({{ inventory_hostname }}) is not currently supported."
  when: ( ansible_os_family != "Debian" and ansible_distribution_release not in ['trusty'] )


- set_fact:
   redis_version={{ redis_install.download_url | basename | regex_replace('^redis-(.*).tar.gz$', '\\1') }}


- name: print redis version extracted from downlod url
  debug: >
    msg="got redis version from redis_install.download_url {{ redis_version }}"
  when: redis_install.method == "src"


- name: Include Debian specific tasks to install from package
  include: "{{ ansible_os_family }}.yml"
  static: no
  when: ansible_os_family == 'Debian' and redis_install.method == "pkg"


- name: Include Debian specific tasks when installing from source
  include: "{{ ansible_os_family }}-SRC.yml"
  static: no
  when: ansible_os_family == "Debian" and redis_install.method == "src"
